apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jibby
spec:
  serviceName: jibby
  selector:
    matchLabels:
      app: jibby
  template:
    metadata:
      labels:
        app: jibby
    spec:
      containers:
        - name: jibby
          image: IMAGE_PATH
          ports:
            - containerPort: 8080

