apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ values.crumb }}
spec:
  serviceName: ${{ values.crumb }}
  selector:
    matchLabels:
      app: ${{ values.crumb }}
  template:
    metadata:
      labels:
        app: ${{ values.crumb }}
    spec:
      containers:
        - name: ${{ values.crumb }}
          image: IMAGE_PATH
          ports:
            - containerPort: 8080

